name: RTx-Calendar
version: 0.02
abstract: Calendar view
author: Nicolas Chuche <nchuche@barna.be>
license: perl
distribution_type: module
requires:
  RT: 3.6
  DateTime: 0
  DateTime::Set: 0
no_index:
  directory:
    - html
    - inc
generated_by: handmade
